name: Manual Workflow
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Setup environment
    - name: Setup up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    # Step 3: Install dependiencies
    - name: Install Jest 
      run: npm install jest

    # Step 4: Run tests 
    - name: Run tests
      run: npx jest --coverage
